### ISSUE TITLE
非常希望帮助，可有偿

### ISSUE THREAD

**Issue by yyystg** [ms303956362/myexercise#59]
请问你的AVC的代码是复现的哪篇文献，可以提供一下么。可有偿

**Comment by ms303956362** [comment]
> 请问你的AVC的代码是复现的哪篇文献，可以提供一下么。可有偿

https://ieeexplore.ieee.org/document/9076841，复现结果有点问题，不太好

**Comment by ms303956362** [comment]
> 请问你的AVC的代码是复现的哪篇文献，可以提供一下么。可有偿

https://ieeexplore.ieee.org/document/9076841
复现有点问题，不太好，后续没有排查

**Comment by yyystg** [comment]
可以加个微信么？我是电气专业的研一小白，专业是深度强化学习方向。想跟你购买一些代码之类的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ms303956362/myexercise"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ms303956362/myexercise] 非常希望帮助，可有偿 (Issue #59)





  
请问你的AVC的代码是复现的哪篇文献，可以提供一下么。可有偿
  
https://ieeexplore.ieee.org/document/9076841
 复现有点问题，不太好，后续没有排查

**Comment by ms303956362** [comment]
> 可以加个微信么？我是电气专业的研一小白，专业是深度强化学习方向。想跟你购买一些代码之类的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ms303956362/myexercise" ***@***.***&gt;; 发送时间:&nbsp;2022年4月18日(星期一) 下午3:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ms303956362/myexercise] 非常希望帮助，可有偿 (Issue #59) 请问你的AVC的代码是复现的哪篇文献，可以提供一下么。可有偿 https://ieeexplore.ieee.org/document/9076841 复现有点问题，不太好，后续没有排查 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

直接用吧，不用买了，放出来就是可以开源的

**Comment by yyystg** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月18日(星期一) 下午3:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ms303956362/myexercise] 非常希望帮助，可有偿 (Issue #59)





  
可以加个微信么？我是电气专业的研一小白，专业是深度强化学习方向。想跟你购买一些代码之类的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ms303956362/myexercise" @.&gt;; 发送时间:&nbsp;2022年4月18日(星期一) 下午3:15 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ms303956362/myexercise] 非常希望帮助，可有偿 (Issue #59) 请问你的AVC的代码是复现的哪篇文献，可以提供一下么。可有偿 https://ieeexplore.ieee.org/document/9076841 复现有点问题，不太好，后续没有排查 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
直接用吧，不用买了，放出来就是可以开源的
